export const books = [
    {      
      id: 1,
        title: "The Great Gatsby",
        image: "https://m.media-amazon.com/images/I/81QuEGw8VPL._SL1500_.jpg",
        description: "A novel about the American dream and the disillusionment of the 1920s.",
        author: "F. Scott Fitzgerald",
        releaseYear: "1925",
        rating: 4.2,
        pages: 180,
        category: "Fiction",
    },
    {
      id: 2,
      title: "Atomic Habits",
      image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1655988385l/40121378.jpg",
      description:
        "A guide to building good habits and breaking bad ones through small, incremental changes.",
      author: "James Clear",
      releaseYear: "2018",
      rating: 4.4,
      pages: 320,
      category: "Self-help",
    },
    {
      id: 3,
      title: "The Alchemist",
      image: "https://mir-s3-cdn-cf.behance.net/project_modules/max_3840/90822f55620761.598bf1d73ae0c.jpg",
      description:
        "A philosophical journey of self-discovery and following one's dreams.",
      author: "Paulo Coelho",
      releaseYear: "1988",
      rating: 3.9,
      pages: 208,
      category: "Fiction",
    },
    {
        id: 4,
        title: "Sapiens: A Brief History of Humankind",
        image: "https://m.media-amazon.com/images/I/713jIoMO3UL._SL1500_.jpg",
        description: "An exploration of the history and impact of Homo sapiens.",
        author: "Yuval Noah Harari",
        releaseYear: "2011",
        rating: 4.5,
        pages: 443,
        category: "Non-Fiction",
    },
    {
        id: 5,
        title: "Educated",
        image: "https://m.media-amazon.com/images/I/51FeA1fnqtL._SL1100_.jpg",
        description: "A memoir about a woman's quest for knowledge and self-discovery.",
        author: "Tara Westover",
        releaseYear: "2018",
        rating: 4.7,
        pages: 334,
        category: "Memoir",
    },
    {
        id: 6,
        title: "Becoming",
        image: "https://m.media-amazon.com/images/I/81KGjsBXQ7L._SL1500_.jpg",
        description: "The memoir of Michelle Obama, detailing her life from childhood to the White House.",
        author: "Michelle Obama",
        releaseYear: "2018",
        rating: 4.6,
        pages: 426,
        category: "Memoir",
    },
    {
        id: 7,
        title: "The Silent Patient",
        image: "https://m.media-amazon.com/images/I/81JJPDNlxSL._SL1500_.jpg",
        description: "A psychological thriller about a woman who stops speaking after committing a violent act.",
        author: "Alex Michaelides",
        releaseYear: "2019",
        rating: 4.2,
        pages: 336,
        category: "Thriller",
    },
    {
        id: 8,
        title: "Where the Crawdads Sing",
        image: "https://m.media-amazon.com/images/I/81e+mSqZvnL._SL1500_.jpg",
        description: "A coming-of-age story intertwined with a murder mystery set in the marshes of North Carolina.",
        author: "Delia Owens",
        releaseYear: "2018",
        rating: 4.8,
        pages: 368,
        category: "Fiction",
    },
    {
        id: 9,
        title: "The Midnight Library",
        image: "https://m.media-amazon.com/images/I/81J6APjwxlL._SL1500_.jpg",
        description: "A story about a library that allows one to explore alternate lives.",
        author: "Matt Haig",
        releaseYear: "2020",
        rating: 4.1,
        pages: 288,
        category: "Fantasy",
    },
    {
        id: 10,
        title: "Dune",
        image: "https://m.media-amazon.com/images/I/71-1WBgjGoL._SL1500_.jpg",
        description: "A science fiction epic about politics, religion, and ecology on a desert planet.",
        author: "Frank Herbert",
        releaseYear: "1965",
        rating: 4.6,
        pages: 412,
        category: "Sci-Fi",
    },
  ];
  
  export default books;
  